### ISSUE TITLE
md5sum command not found in MacOS

### ISSUE THREAD

**Issue by arthurfferreira** [aogburn/yatda#16]
In MacOS it can't check upstream version because there's no `md5sum`:

```shell
aferreir@aferreir-mac 2023-08-16 % sh ~/yatda.sh jstack_threaddump_03aug2023.out
Checking script update. Use option '-u never' to skip the update check
/Users/aferreir/yatda.sh: line 157: md5sum: command not found
``` 

To check md5sum in MacOS, we have to run `md5 -r filename.ext`

**Comment by aogburn** [comment]
That's update specific error chatter so could be completely avoided with '-u never'.  I'm not testing on any MacOS platform, but could accept a PR if you want to test and submit.  I'm not sure if that won't lead to a larger can of worms or not to work on MacOS.

**Comment by aogburn** [comment]
https://github.com/aogburn/yatda/commit/6186c83085a8acfaec7b2254671bb8f0f0b70126
