### ISSUE TITLE
yatda.sh: line 161: [: eaf590d3c184e6f1c931898f0ec1fe8b binary operator expected

### ISSUE THREAD

**Issue by arthurfferreira** [aogburn/yatda#17]
Ignoring the message about md5sum (that's on another issue already created) it also complains about the binary operator

```shell
aferreir@aferreir-mac 2023-08-16 % sh ~/yatda.sh jstack_threaddump_03aug2023.out
Checking script update. Use option '-u never' to skip the update check
/Users/aferreir/yatda.sh: line 157: md5sum: command not found
/Users/aferreir/yatda.sh: line 161: [: eaf590d3c184e6f1c931898f0ec1fe8b: binary operator expected
``` 

This seems to be related to the `$NEWSUM` variable.

**Comment by aogburn** [comment]
This is a side effect of md5sum not being found so the $SUM variable is null.  So this is not really a separate issue.
